export const main = document.querySelector(`main`);
export const header = document.querySelector("header");
export const leftPart = document.querySelector(`header .left`);
export const rightPart = document.querySelector(`header .right`);
export const name = document.querySelector('header h1')
export const summary = document.querySelector(`.summary`);
export const body = document.querySelector("body");
export const html = document.querySelector("html");
export const ulHeader = document.querySelector(`header ul`);